{{- if not .Values.postgres.ha.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "hello-db.postgresName" . }}
  labels:
    {{- include "hello-db.labels" . | nindent 4 }}
type: Opaque
stringData:
  POSTGRES_DB: {{ .Values.postgres.database | quote }}
  POSTGRES_USER: {{ .Values.postgres.username | quote }}
  POSTGRES_PASSWORD: {{ .Values.postgres.password | quote }}
{{- end }}
