{{- if not .Values.postgres.ha.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "hello-db.postgresName" . }}
  labels:
    {{- include "hello-db.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: postgres
  ports:
    - name: postgres
      port: 5432
      targetPort: postgres
{{- end }}
